# Generated by Django 5.2.3 on 2025-06-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del campeonato')),
                ('patrocinador', models.CharField(max_length=100, verbose_name='Patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año del campeonato')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentario adicional')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_ganadores', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del equipo')),
                ('siglas', models.CharField(max_length=10)),
                ('twitter', models.CharField(max_length=50, verbose_name='Cuenta de Twitter')),
                ('campeonatos', models.ManyToManyField(through='futbolec.CampeonatoEquipo', to='futbolec.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='campeonatoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_ganados', to='futbolec.equipo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquipo', to='futbolec.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del jugador')),
                ('posicion', models.CharField(choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('mediocampo', 'Mediocampo'), ('delantero', 'Delantero')], max_length=30)),
                ('numero', models.IntegerField(verbose_name='Número en camiseta')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipo')),
            ],
        ),
    ]
